#-------------------------------
# General Site Settings
baseURL = ""
languageCode = "en-us"
title = "Danto"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 12


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "How to"
    url = "/tags/how-to/"
    weight = 1

  [[menu.main]]
    name = "Reviews"
    url = "/tags/review/"
    weight = 2

  [[menu.main]]
    name = "Indoor Cycling"
    url = "/tags/indoor-cycling"
    weight = 3

  [[menu.main]]
    name = "Rides"
    url = "/tags/bike-rides/"
    weight = 4

  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Contact"


[params]
  logo = "/logo/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo.png"
  description = "Danto is a news and magazine Hugo theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = false
    hero__title = ""
    hero__description = ""


  #-------------------------------
  # Tags Section Settings
  [params.tags_section]
    enable = true
    number_posts = 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
    number_columns = 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.

  [[params.tag]]
    tag = "tags/how-to"
    tag_title = "How to"

  [[params.tag]]
    tag = "tags/review"
    tag_title = "Review"

  [[params.tag]]
    tag = "tags/indoor-cycling"
    tag_title = "Indoor Cycling"

  # You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = false
    section_title = "Meet our authors"


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = "Dedicated to the non-competitive side of cycling, promoting the joy of cycling for fun, exploration, and reconnecting with nature."

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  # Newsletter
  [params.mailchimp]
    enable = false
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "mnqkapwv" # Add your form_id

    # NOTE
    # Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false